# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Proyecto-prototipo' do
  use_frameworks!
  pod 'DeviceKit', '~> 1.3'
  pod 'Alamofire', '~> 5.0.0-beta.3'
  pod 'Kingfisher', '~> 5.0'
  pod 'JGProgressHUD'
end
